{
 "title": "RaibeartRuadh Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Load Avarege",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load-1" }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sda1\", mountpoint=\"/\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Disk read/write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sda\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sda\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "transmit"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "receive"
    }
   ]
  }
 ]
}